version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  backend:
    docker:
      - image: node:18.20.5
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: npm install
      - run:
          name: Start Backend Server
          command: npm start
workflows:
  build-and-deploy:
    jobs:
      - build-node
      - backend:
          requires:
            - build-node